spring:
  application:
    name: sbb
  profiles:
    active: dev
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

  output:
    ansi:
      enabled: always

  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8070

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE